replicaCount: 1

image:
  repository: nginx
  tag: "1.24.0"
  pullPolicy: IfNotPresent

service:
  port: 80

serviceAccount:
  create: false

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: v124-app2.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

autoscaling:
  enabled: false
