---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/pv-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  volumeName: local-pv
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exchange-pvc
  template:
    metadata:
      labels:
        app: exchange-pvc
    spec:
      containers:
      - name: busybox-pvc
        image: busybox
        command: ["sh", "-c", "while true; do date >> /data/data.txt; sleep 5; done"]
        volumeMounts:
        - name: shared-data
          mountPath: /data
      - name: multitool-pvc
        image: wbitt/network-multitool:latest
        command: ["sh", "-c", "tail -f /data/data.txt"]
        volumeMounts:
        - name: shared-data
          mountPath: /data
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: local-pvc
