apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default # ОПЦИОНАЛЬНО: Укажите namespace, если не default
data:
  # КЛЮЧЕВОЙ МОМЕНТ: index.html будет подключен как файл
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Моя страница из ConfigMap</title>
    </head>
    <body>
      <h1>Привет от Kubernetes!</h1>
      <p>Домашнее задание</p>
      <p>Выполнено 1 августа 2025 г.</p>
    </body>
    </html>
